name: Flashlight
main: me.foxyy.Flashlight
version: 1.2
api-version: 1.21
commands:
  flashlight:
    description: Toggles flashlight.
    usage: "Usage: /<command>"
    permission: Flashlight.use
    aliases:
      - fl
  config:
    description: Allows you to modify and view flashlight configuration.
    usage: "Usage: /<command> <config_path> [config_value]"
    permission: Flashlight.config